### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by andrewthad** [ekmett/prelude-extras#7]
This library should probably be marked as deprecated in favor of base (or maybe in favor of transformers for a slightly better backwards-compatibility story).

**Comment by RyanGlScott** [comment]
Now would be as good of a time as any to do it since `free`, the last @ekmett package to depend on `prelude-extras`, removed its `prelude-extras` dependency in version 5.

**Comment by ekmett** [comment]
Works for me.

**Comment by ekmett** [comment]
I've deprecated it on hackage.
